---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: yes

- name: "remove unwanted packages"
  become: true
  apt:
    autoremove: yes

- name: "Install nvm and setup node version 13.8.0"
  become: true
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    nvm -v
    nvm install 13.8.0
    node -v

# - name: "install dependencies."
#   become: true
#   apt:
#     name: ["nodejs", "npm"]
#     state: 13.8.0
#     update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present